# Generated by Django 2.2.3 on 2019-07-11 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20190707_0039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Family',
        ),
    ]
